spring:
  application:
    name: tinder
  datasource:
    url: jdbc:postgresql://localhost:5436/tinder
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    defer-datasource-initialization: true
#    spring:
#      sql:
#        init:
#          mode=always
logging:
  level:
    org.springframework.security.web: DEBUG
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
    org.springframework.data.jpa: DEBUG
