spring:
  application:
    name: tinder
  datasource:
    url: jdbc:postgresql://database:5432/tinder
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    drop-first: false
    default-schema: public

logging:
  level:
    org.springframework.security.web: DEBUG
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
    org.springframework.data.jpa: DEBUG
