-- INSERT INTO roles (role_name) VALUES ('user');
-- INSERT INTO roles (role_name) VALUES ('manager');
-- INSERT INTO roles (role_name) VALUES ('employee');
-- INSERT INTO roles (role_name) VALUES ('boss');