spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NikaT1/tinder-configs.git
          search-paths:
            - config
          default-label: main
        native:
          search-locations: file:./config/

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/