spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/silly-pepper/crossplanet-tinder-monolit
          search-paths:
            - config
          default-label: lab2
        native:
          search-locations: file:./config/
  port: 8888