spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/silly-pepper/crossplanet-tinder-monolit
          search-paths:
            - config
          default-label: lab2
        native:
          search-locations: file:./config/

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/