name: Build Docker Images and Push to Registry

on:
  push:
    branches:
      - 'main'
      - 'lab3-milestone'
  pull_request:

env:
  JDK_VERSION: 17
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.sha }}  # Используем хеш коммита как тег

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, user-data-service, spacesuit-service, location-service, fabric-texture-service, eureka-service, config-service, gateway-service]  # Указываем список сервисов
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for ${{ matrix.service }}
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }} .
      
      - name: Push Docker image for ${{ matrix.service }}
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
